server:
  port: 8088
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

#  server.servlet.encoding.force=true
#  server.servlet.encoding.charset=UTF-8

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: xinda

jwt:
  secret: ca6a55220b2c474f9ea9b049452503cc